// Import everything from @litquid/runtime — never from 'lit' directly.
// The runtime ensures lit-element-hydrate-support is patched before LitElement
// initialises, so SSR hydration always works regardless of bundler order.
import { LitQuidElement, css, type TemplateResult } from '@litquid/runtime';
import { getTemplate } from './templates/my-component.template.js';

/**
 * MyComponent - user card. Shared template with server (my-component.liquid).
 *
 * SSR path: DotLiquid renders the .liquid file → lit-part markers wrap each binding →
 *   @lit-labs/ssr-client hydrates the existing DOM and applies reactivity.
 *
 * CSR path: getTemplate() (generated by the Rust preprocessor from the same .liquid file)
 *   renders the component fresh via Lit.
 *
 * @element my-component
 */
export class MyComponent extends LitQuidElement {
    static properties = {
        firstName: { type: String },
        lastName:  { type: String },
        age:       { type: Number },
        role:      { type: String },
    };

    // Styles mirror the <style> block in my-component.liquid so SSR and CSR look identical.
    static styles = css`
        :host {
            display: block;
            font-family: system-ui, -apple-system, sans-serif;
        }
        .card {
            padding: 1rem 1.25rem;
            border: 1px solid #e0e0e0;
            border-radius: 10px;
            background: #fff;
            box-shadow: 0 1px 3px rgba(0,0,0,.06);
        }
        .name {
            margin: 0 0 0.15rem;
            font-size: 0.95rem;
            font-weight: 600;
            color: #111;
        }
        .meta {
            margin: 0;
            font-size: 0.82rem;
            color: #888;
        }
    `;

    firstName = '';
    lastName  = '';
    age       = 0;
    role      = '';

    protected override renderTemplate(): TemplateResult {
        return getTemplate(this);
    }
}

customElements.define('my-component', MyComponent);
