//! C# server-side render emitter.
//!
//! Generates a static class with a typed `Render(...)` method that produces
//! SSR HTML with `<!--lit-part-->` markers — no Liquid engine required at runtime.

use crate::{Binding, ParsedTemplate};
use super::TargetEmitter;

/// Emits a C# class with a typed `Render(...)` method.
pub struct CSharpEmitter {
    /// C# namespace for the generated class (e.g., `"LitQuid.Generated"`)
    pub namespace: String,
}

impl TargetEmitter for CSharpEmitter {
    fn file_extension(&self) -> &str {
        "cs"
    }

    fn emit(&self, template_name: &str, parsed: &ParsedTemplate) -> String {
        let class_name = to_pascal_case(template_name);

        // Unique parameter names in document order
        let mut seen: Vec<&str> = Vec::new();
        for b in &parsed.bindings {
            if !seen.contains(&b.var_name.as_str()) {
                seen.push(&b.var_name);
            }
        }
        let param_decls = seen
            .iter()
            .map(|name| format!("string {}", name))
            .collect::<Vec<_>>()
            .join(", ");

        // Build string.Concat argument list and collect needed helpers
        let mut concat_items: Vec<String> = Vec::new();
        // (filter_name → method_body), deduplicated, insertion-ordered
        let mut helpers: Vec<(String, String)> = Vec::new();

        let open_tag = parsed
            .template_open_tag
            .as_deref()
            .unwrap_or("<template shadowrootmode=\"open\">");

        // "<template ...>\n<!--lit-part " , Digest , "-->\n[static[0]]..."
        concat_items.push(format!(
            "\"{}\\n<!--lit-part \"",
            escape_cs(open_tag)
        ));
        concat_items.push("Digest".to_string());

        if parsed.bindings.is_empty() {
            let inner = parsed.static_segments.first().map(|s| s.as_str()).unwrap_or("");
            concat_items.push(format!(
                "\"-->\\n{}\\n<!--/lit-part-->\\n</template>\"",
                escape_cs(inner)
            ));
        } else {
            // Merge "-->\n" prefix with first static segment
            concat_items.push(format!(
                "\"-->\\n{}\"",
                escape_cs(&parsed.static_segments[0])
            ));

            let last = parsed.bindings.len() - 1;
            for (i, binding) in parsed.bindings.iter().enumerate() {
                concat_items.push("\"<!--lit-part-->\"".to_string());

                let (expr, binding_helpers) = build_expr(binding);
                concat_items.push(expr);
                for (key, body) in binding_helpers {
                    if !helpers.iter().any(|(k, _)| k == &key) {
                        helpers.push((key, body));
                    }
                }

                concat_items.push("\"<!--/lit-part-->\"".to_string());

                let next = &parsed.static_segments[i + 1];
                if i == last {
                    concat_items.push(format!(
                        "\"{}\\n<!--/lit-part-->\\n</template>\"",
                        escape_cs(next)
                    ));
                } else {
                    concat_items.push(format!("\"{}\"", escape_cs(next)));
                }
            }
        }

        let concat_body = concat_items
            .iter()
            .map(|item| format!("            {}", item))
            .collect::<Vec<_>>()
            .join(",\n");

        let helpers_section: String = helpers
            .iter()
            .map(|(_, body)| format!("\n    {}", body))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            "// Generated by litquid — do not edit.\n\
             // Source: {name}.liquid\n\
             \n\
             namespace {ns};\n\
             \n\
             public static class {class}Template\n\
             {{\n\
             \x20   public const string Digest = \"{digest}\";\n\
             \n\
             \x20   public static string Render({params})\n\
             \x20   {{\n\
             \x20       return string.Concat(\n\
             {concat}\n\
             \x20       );\n\
             \x20   }}{helpers}\n\
             }}\n",
            name = template_name,
            ns = self.namespace,
            class = class_name,
            digest = parsed.digest,
            params = param_decls,
            concat = concat_body,
            helpers = helpers_section,
        )
    }
}

/// Build the C# expression for a binding and collect any needed helper methods.
fn build_expr(binding: &Binding) -> (String, Vec<(String, String)>) {
    let mut expr = binding.var_name.clone();
    let mut helpers: Vec<(String, String)> = Vec::new();

    for (filter_name, args) in &binding.filters {
        let (new_expr, helper) = apply_filter(&expr, filter_name, args);
        expr = new_expr;
        if let Some((key, body)) = helper {
            if !helpers.iter().any(|(k, _)| k == &key) {
                helpers.push((key, body));
            }
        }
    }

    (expr, helpers)
}

/// Translate a single Liquid filter to its C# equivalent.
/// Returns `(expression, Some((helper_key, helper_body)))` when a private method is needed.
fn apply_filter(
    expr: &str,
    filter: &str,
    args: &[String],
) -> (String, Option<(String, String)>) {
    let a0 = args.first().map(|s| s.as_str()).unwrap_or("");
    let a1 = args.get(1).map(|s| s.as_str()).unwrap_or("");

    match filter {
        "capitalize" => (
            format!("Capitalize({})", expr),
            Some((
                "capitalize".to_string(),
                "private static string Capitalize(string s) =>\n        \
                 string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1).ToLower();"
                    .to_string(),
            )),
        ),
        "upcase"     => (format!("{}.ToUpperInvariant()", expr), None),
        "downcase"   => (format!("{}.ToLowerInvariant()", expr), None),
        "strip"      => (format!("{}.Trim()", expr), None),
        "append"     => (format!("({} + {})", expr, a0), None),
        "prepend"    => (format!("({} + {})", a0, expr), None),
        "default"    => (format!("(string.IsNullOrEmpty({0}) ? {1} : {0})", expr, a0), None),
        "size"       => (format!("{}.Length.ToString()", expr), None),
        "plus"       => (format!("((double.Parse({}) + {}).ToString())", expr, a0), None),
        "minus"      => (format!("((double.Parse({}) - {}).ToString())", expr, a0), None),
        "times"      => (format!("((double.Parse({}) * {}).ToString())", expr, a0), None),
        "divided_by" => (format!("((double.Parse({}) / {}).ToString())", expr, a0), None),
        "modulo"     => (format!("((double.Parse({}) % {}).ToString())", expr, a0), None),
        "round"      => (
            format!(
                "(Math.Round(double.Parse({}), MidpointRounding.AwayFromZero).ToString())",
                expr
            ),
            None,
        ),
        "floor"      => (format!("(Math.Floor(double.Parse({})).ToString())", expr), None),
        "ceil"       => (format!("(Math.Ceiling(double.Parse({})).ToString())", expr), None),
        "abs"        => (format!("(Math.Abs(double.Parse({})).ToString())", expr), None),
        "at_least"   => (format!("(Math.Max(double.Parse({}), {}).ToString())", expr, a0), None),
        "at_most"    => (format!("(Math.Min(double.Parse({}), {}).ToString())", expr, a0), None),
        "truncate"   => {
            let n = if a0.is_empty() { "50" } else { a0 };
            (
                format!(
                    "({e}.Length > {n} ? {e}.Substring(0, {n}) + \"...\" : {e})",
                    e = expr,
                    n = n
                ),
                None,
            )
        }
        "replace"    => (format!("{}.Replace({}, {})", expr, a0, a1), None),
        "remove"     => (format!("{}.Replace({}, \"\")", expr, a0), None),
        "url_encode" => (format!("Uri.EscapeDataString({})", expr), None),
        "url_decode" => (format!("Uri.UnescapeDataString({})", expr), None),
        unknown => {
            eprintln!(
                "litquid warning: unknown filter '{}' for C# emit, dropping — \
                 add explicit csr arg to suppress",
                unknown
            );
            (expr.to_string(), None)
        }
    }
}

/// Convert kebab-case or snake_case to PascalCase (`my-component` → `MyComponent`).
fn to_pascal_case(s: &str) -> String {
    s.split(|c| c == '-' || c == '_')
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Escape a string for use inside a C# double-quoted string literal.
fn escape_cs(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"'  => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c    => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("my-component"), "MyComponent");
        assert_eq!(to_pascal_case("user_card"), "UserCard");
        assert_eq!(to_pascal_case("simple"), "Simple");
    }

    #[test]
    fn test_escape_cs() {
        assert_eq!(escape_cs("hello \"world\""), "hello \\\"world\\\"");
        assert_eq!(escape_cs("line1\nline2"), "line1\\nline2");
        assert_eq!(escape_cs("back\\slash"), "back\\\\slash");
    }
}
